export const IMAGES = {
    welcomLogo: require('./welcomLogo.png'),
    addAccButton: require('./addAccButton.png'),
    addGoogleButton: require('./addGoogleButton.png'),
    addFacebookButton: require('./addFacebookButton.png'),
    addGithubButton: require('./addGithubButton.png'),
    marvelIcon: require('./marvelIcon.png'),
    dcIcon: require('./dcIcon.png'),
    warnerIcon: require('./warnerIcon.png'),
    netflixIcon: require('./netflixIcon.png'),
    cancel: require('./cancel.png'),
    yourName: require('./yourName.png'),
    yourEmail: require('./yourEmail.png'),
    yourPassword: require('./yourPassword.png'),
    yourSername: require('./yourSername.png'),
};